version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: els
    environment:
      - discovery.type=single-node
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
    networks:
      - elk
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  kibana:
    image: kibana:8.15.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://els:9200

networks:
  elk:
    driver: bridge

volumes:
  esdata: